a, b = input().split()
sum = int(a) + int(b)
sub = int(a) - int(b)
mul = int(a) * int(b)
div1 = int(int(a) / int(b))
div2 = int(a) % int(b)
div3 = int(a) / int(b)

print(sum)
print(sub)
print(mul)
print(div1)
print(div2)
print(round(div3, 2))